---

# This playbook assumes the following:
#
#   1. Your default ~/.kube/config points to a running Kubernetes cluster;
#
#   2. You already have Helm and Ansible installed locally.



- name: get database binding
  shell: kubectl get secrets -n {{ namespace }} -l mynamespace -o json
  register: bindingout

- name: set database facts
  set_fact:
    DB_HOST: "{{ bindingout.stdout | from_json ['DB_HOST'] | b64decode }}"
    DB_USER: "{{ bindingout.stdout | from_json ['DB_USER'] | b64decode }}"
    DB_PASSWORD: "{{ bindingout.stdout | from_json ['DB_PASSWORD'] | b64decode }}"
    DB_NAME: "{{ bindingout.stdout | from_json ['DB_NAME'] | b64decode }}"
    DB_PORT: "{{ bindingout.stdout | from_json ['DB_PORT'] | b64decode }}"



################CLONE REPO#######

- name: clone chart repo
  git:
    repo: https://ama.github.com/mariadb/helm-charts.git
    dest: ~/mariadb/charts/repo
    update: yes


################# INSTALL  HELM ###########

- name: "Install chart "
  command: 
    {{ helm_cmd }}
    install
    --kubeconfig {{ kube_config }}
    -f {{ value_chart}} -f {{ override_chart }}
  when: chart.state == 'present'

 

###############ADD REPO######

- name: Add ama chart repo.
  community.kubernetes.helm_repository:
    name: ama
    repo_url: "https://ama.github.io/ama-charts/"

- name: Deploy mariadb Helm chart.
  community.kubernetes.helm:
    name: mariadb
    chart_ref: ama/mariadb
    chart_version: '2.0.7'
    release_namespace: mariadb
    state: present
    values_files:
      - /path/to/values.yaml
      - /path/to/override.yaml
  

    
    
    
    
    